//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extent.ExtentHtmlReporter.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Extent.ExtentHtmlReporter.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachment for this log (optional)..
        /// </summary>
        internal static string LogTestStatusAttachmentDescription {
            get {
                return ResourceManager.GetString("LogTestStatusAttachmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string LogTestStatusAttachmentDisplayName {
            get {
                return ResourceManager.GetString("LogTestStatusAttachmentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs the test status (Pass/Fail) with an optional screenshot attachment..
        /// </summary>
        internal static string LogTestStatusDescription {
            get {
                return ResourceManager.GetString("LogTestStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The detail description of this log..
        /// </summary>
        internal static string LogTestStatusDetailsDescription {
            get {
                return ResourceManager.GetString("LogTestStatusDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string LogTestStatusDetailsDisplayName {
            get {
                return ResourceManager.GetString("LogTestStatusDetailsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Test Status.
        /// </summary>
        internal static string LogTestStatusDisplayName {
            get {
                return ResourceManager.GetString("LogTestStatusDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status of this log (Pass/Fail)..
        /// </summary>
        internal static string LogTestStatusPassFailDescription {
            get {
                return ResourceManager.GetString("LogTestStatusPassFailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LogTestStatusPassFailDisplayName {
            get {
                return ResourceManager.GetString("LogTestStatusPassFailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}.
        /// </summary>
        internal static string MetadataValidationError {
            get {
                return ResourceManager.GetString("MetadataValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity is valid only inside.
        /// </summary>
        internal static string ParentScope_ValidationMessage {
            get {
                return ResourceManager.GetString("ParentScope_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Report Scope.
        /// </summary>
        internal static string TestcaseReportScope {
            get {
                return ResourceManager.GetString("TestcaseReportScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the scope of a test report. Each test report can contain multiple testcases..
        /// </summary>
        internal static string TestcaseReportScopeDescription {
            get {
                return ResourceManager.GetString("TestcaseReportScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the folder where the test report will be created. If the folder does not exist, it will be created.
        ///
        ///Two files (index.html and dashboard.html) will be created in this folder. If they exist, they will be removed..
        /// </summary>
        internal static string TestcaseReportScopePathDescription {
            get {
                return ResourceManager.GetString("TestcaseReportScopePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Report Path.
        /// </summary>
        internal static string TestcaseReportScopePathDisplayName {
            get {
                return ResourceManager.GetString("TestcaseReportScopePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testcase Scope.
        /// </summary>
        internal static string TestcaseScope {
            get {
                return ResourceManager.GetString("TestcaseScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The testcase description..
        /// </summary>
        internal static string TestcaseScopeDescDescription {
            get {
                return ResourceManager.GetString("TestcaseScopeDescDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testcase Description.
        /// </summary>
        internal static string TestcaseScopeDescDisplayName {
            get {
                return ResourceManager.GetString("TestcaseScopeDescDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the scope of a testcase..
        /// </summary>
        internal static string TestcaseScopeDescription {
            get {
                return ResourceManager.GetString("TestcaseScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The testcase name..
        /// </summary>
        internal static string TestcaseScopeNameDescription {
            get {
                return ResourceManager.GetString("TestcaseScopeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testcase Name.
        /// </summary>
        internal static string TestcaseScopeNameDisplayName {
            get {
                return ResourceManager.GetString("TestcaseScopeNameDisplayName", resourceCulture);
            }
        }
    }
}
